version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - expensex_pg_data:/bitnami/postgresql

volumes:
  expensex_pg_data:
